
FROM nginx:stable-alpine

COPY nginx.config /etc/nginx/nginx.conf

COPY page.html /usr/share/nginx/html/index.html

COPY .htpasswd /etc/nginx/.htpasswd

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
