default:
  image: docker
  services:
    - "docker:dind"
  before_script:
    - docker info

build-job:
  stage: build
  script: 
    - unset DOCKER_HOST
    - docker compose build
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production