build-job:
  stage: build
  script: 
    - docker context ls 
    - docker context use default 
    - unset DOCKER_HOST
    - docker compose build
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production