build-job:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  script: 
    - dockerd
    - docker compose build
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production