default:
  image: docker
  services:
    - "docker:dind"
  before_script:
    - docker info

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-job:
  stage: build
  script: 
    - unset DOCKER_HOST
    - docker compose build -t $IMAGE_TAG
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production