default:
  image: docker:stable
  services:
    - name: docker:24.0-dind
      alias: docker
  before_script:
    - docker info

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build-job:
  stage: build
  script: 
    - unset DOCKER_HOST
    - docker compose build
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production