default:
  image: docker
  services:
    - "docker:dind"
  before_script:
    - docker info
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

build-job:
  stage: build
  script: 
    - dockerd
    - docker compose build
    - echo "Built"

test-job: 
  stage: test
  script: 
    - echo "testing"

deploy:
  stage: deploy
  script: 
    - docker compose up 
    - echo "Deployed"
  environment: production