default:
  image: docker:stable
  services: 
    - name: docker:dind  
      command: ["--tls=false"]
  before_script:
  - apk add --no-cache docker-compose curl
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - docker-compose build

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - htpasswd -b -c /var/opt/gitlab/nginx/conf/ $USERNAME $PASSWORD
    - docker-compose up --build -d
    - curl -u "$USERNAME:$PASSWORD" http://docker:8198/request

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

