version: "3"
services:
  pythonserver_1:
    container_name: pythonServer1
    command: python3 App.py 
    build:
      dockerfile: DockerFile
      context: ./pythonServer
    networks:
      - loadbalancing
    ports:
      - "8210:8210"
  nodeserver1:
    command: npm start
    build:
      dockerfile: DockerFile
      context: ./nodeServer
    environment: 
      - PORT=8199
    #ports: 
    #  - "8199:8199"
    networks:
      - loadbalancing
  nodeserver2:
    command: npm start
    build:
      dockerfile: DockerFile
      context: ./nodeServer
    environment: 
      - PORT=8199
    #ports: 
    #  - "8199:8199"
    networks:
      - loadbalancing
  nodeserver3:
    command: npm start
    build:
      dockerfile: DockerFile
      context: ./nodeServer
    environment: 
      - PORT=8199
    #ports: 
    #  - "8199:8199"
    networks:
      - loadbalancing
  nginx:
    build: 
      dockerfile: DockerFile
      context: ./nginxServer
    #environment: 
    #  - PORT=8198
    ports: 
      - "8198:80"
    #expose: 
    #  - 8198
    networks:
      - loadbalancing
    depends_on:
      - nodeserver1
      - nodeserver2
      - nodeserver3

networks:
  loadbalancing: