services:
  pythonserver_1:
    container_name: pythonServer1
    command: python3 App.py 
    build:
      dockerfile: DockerFile
      context: ./pythonServer
    networks:
      - loadbalancing
    ports:
      - "8210:8210"
  nodeserver:
    command: npm start
    build:
      dockerfile: DockerFile
      context: ./nodeServer
    environment: 
      - PORT=8199
    #ports: 
    #  - "8199:8199"
    deploy:
      replicas: 4
    networks:
      - loadbalancing
  nginx:
    build: 
      dockerfile: DockerFile
      context: ./nginxServer
    #environment: 
    #  - PORT=8198
    ports: 
      - "8198:80"
    #expose: 
    #  - 8198
    networks:
      - loadbalancing
    depends_on:
      - nodeserver

networks:
  loadbalancing: