services:
  pythonserver:
    container_name: pythonServer
    command: python3 App.py 
    build:
      dockerfile: DockerFile
      context: ./pythonServer
    ports:
      - "8210:8210"
    expose:
      - 8210
  nodeserver:
    command: npm start
    build:
      dockerfile: DockerFile
      context: ./nodeServer
    ports:
      - "8199:8199"
    expose:
      - 8199


    
